### ISSUE TITLE
NetDb: HandleDatabaseStoreMsg: 'GunzipImpl: Put caught exception 'Inflator: error in compressed block''

### ISSUE THREAD

**Issue by anonimal** [monero-project/kovri#538]
**By submitting this issue, I confirm the following:**

- I have read and understood the [contributor guide](https://github.com/monero-project/kovri/blob/master/doc/CONTRIBUTING.md).
- I have checked that the issue I am reporting can be replicated or that the feature I am suggesting is not present.
- I have checked opened or recently closed [pull requests](https://github.com/monero-project/kovri/pulls) for existing solutions/implementations to my issue/suggestion.

*Place an X inside the bracket to confirm*
- [X] I confirm.

---

Roughly ~5 days ago (~2 days after writing [this comment](https://trac.i2p2.de/ticket/1915#comment:8) in java I2P's trac), all test routers began segfaulting with similar (gunzip) related errors (for us, at the core level).  I've never seen this issue before, and we've been enjoying weeks/months+ of segfault-free runtime. Logs + backtraces show that this is a new issue:

```
[2017.01.24 22:58:51.069654] [0x00007fffebfff700] [debug]  NetDb: DatabaseStore
[2017.01.24 22:58:51.069718] [0x00007fffebfff700] [debug]  NetDb: RouterInfo
[2017.01.24 22:58:51.069851] [0x00007fffebfff700] [error]  GunzipImpl: Put caught exception 'Inflator: error in compressed block'
[2017.01.24 22:58:51.069958] [0x00007fffebfff700] [error]  IdentityEx: identity buffer length 0 is too small
```
```
[2017.01.24 22:14:46.072220] [0x0000000805008000] [debug]  NetDb: DatabaseStore
[2017.01.24 22:14:46.072240] [0x0000000805008000] [debug]  NetDb: RouterInfo
[2017.01.24 22:14:46.073597] [0x0000000805008000] [error]  GunzipImpl: Put caught exception 'Inflator: error in compressed block'
[2017.01.24 22:14:46.073631] [0x0000000805008000] [debug]  NetDb: new RouterInfo added
[2017.01.24 22:14:46.073648] [0x0000000805008000] [error]  IdentityEx: identity buffer length 0 is too small
```
```
[2017.01.22 20:54:07.787485] [0xb42fab40] [error]  GunzipImpl: Put caught exception 'Gunzip: CRC check error'
[2017.01.22 20:54:07.787554] [0xb42fab40] [error]  IdentityEx: identity buffer length 1 is too small
```
#### Before identity verification
```
#9  0x0000000000ed836d in kovri::core::RouterInfo::ReadFromBuffer (this=0x7fffe0009410, verify_signature=true) at /home/anonimal/kovri/src/core/router/info.cc:149
        len = -64
```
##### DSM / RI
```
#12 0x0000000000ee6bf9 in kovri::core::NetDb::HandleDatabaseStoreMsg (this=0x153d3c0 <kovri::core::netdb>, m=std::shared_ptr (count 2, weak 0) 0x7fffdc2d0c90) at /home/anonimal/kovri/src/core/router/net_db/impl.cc:543
        decompressor = {m_GunzipPimpl = std::unique_ptr<kovri::core::Gunzip::GunzipImpl> containing 0x7fffe0206da0}
        uncompressed = {
          _M_elems = "\220<E4><FF><EB><FF>\177\000\000\004\222<D2>\000\000\000\000\000<BC><A5>\t<E0><FF>\177\000\000x\023\000<E0><FF>\177\000\000<BC><A5>\t<E0><FF>\177\000\000 <E6><FF><EB><FF>\177\000\000<B0><E4><FF><EB><FF>\177\000\000\063\215<D2>\000\000\000\000\000<E0><E4><FF><EB><FF>\177\000\000x\023\000<E0><FF>\177\000\000<F0><E4><FF><EB><FF>\177\000\000g\210<D2>\000\000\000\000\000 <E9><FF><EB><FF>\177\000\000<BC><A5>\t<E0><FF>\177\000\000x\023\000<E0><FF>\177\000\000 <E5><FF><EB><FF>\177\000\000<BC><A5>\t<E0><FF>\177\000\000\000<D1>|<E6><C9><D1>m/\020<E5><FF><EB><FF>\177\000\000J\203<D2>\000\000\000\000\000<BC><A5>\t<E0><FF>\177\000\000 <E5><FF><EB><FF>\177\000\000\060<E5><FF><EB><FF>\177\000\000<E2>\004<D3>\000\000\000\000\000x\023\000<E0><FF>\177\000\000"...}
        uncompressed_size = 0
```
These number don't add up - and integer overflow has proven itself to be common in the legacy code that we forked from (also, the identity (and parts of the NetDb) implementation is, unfortunately, still legacy code (see #366) and has always been problematic in it's own right). The issue may possibly be a *new* cryptopp issue, or elsewhere in the codebase (I'll just need to sit down and confirm).

We can fix things our side but I suspect the cause being problem router(s) on the network. Malicious or not, I don't know, but I suspect that they are very recent additions. If the DSM isn't garbage, maybe it can point us in a direction.

Backtraces attached.

[kovri-ubu-64.log.txt](https://github.com/monero-project/kovri/files/728325/kovri-ubu-64.log.txt)
[kovri-freebsd-64.log.txt](https://github.com/monero-project/kovri/files/728327/kovri-freebsd-64.log.txt)

**Comment by anonimal** [comment]
```
&anonimal       On an unrelated note, a trivial hotfix is working for #538: routers on all platforms are still online after ~22 hours; logs show success.
&anonimal       In hindsight, what we really need is an exception dispatcher for the crypto impl if not globally (or maybe a global custom exception class).
&anonimal       I can send/merge the hotfix and #538 will end up needing more research for the core of the issue - but at least it won't be a blocker.
```

**Comment by anonimal** [comment]
Unable to reproduce the handled exception on all platforms for over a month now. It appears the problem router(s) have disappeared.

Closing since, should they return, there appears to be no negative impact on our router. If the problem persists, we should re-open this issue.
