### ISSUE TITLE
Clang does not like the Release build

### ISSUE THREAD

**Issue by anonimal** [monero-project/kovri#993]
---
**By submitting this issue, I confirm the following:**

- I have read and understood the developer guide in [kovri-docs](https://github.com/monero-project/kovri-docs).
- I have checked that the issue I am reporting can be replicated or that the feature I am suggesting is not present.
- I have checked opened or recently closed [pull requests](https://github.com/monero-project/kovri/pulls) for existing solutions/implementations to my issue/suggestion.
---

From https://aur.archlinux.org/cgit/aur.git/commit/?h=kovri&id=ac0da4939ea49d1323417643facf345f5d403c87:

```
    SIGSEGV with clang on Arch Linux only, not reproducible with gcc.
    
      clang version 6.0.1 (tags/RELEASE_601/final)
      Target: x86_64-pc-linux-gnu
      Thread model: posix
      InstalledDir: /usr/bin
    
      Thread 12 "kovri" received signal SIGSEGV, Segmentation fault.
      [Switching to Thread 0x7fffeaffd700 (LWP 9695)]
      0x00005555556d8103 in ?? ()
      (gdb) bt
      #0  0x00005555556d8103 in ?? ()
      #1  0x0000555555719244 in ?? ()
      #2  0x000055555566e8ed in ?? ()
      #3  0x00005555556d2ee9 in ?? ()
      #4  0x00005555556f4319 in ?? ()
      #5  0x00005555556f3d66 in
      boost::asio::detail::scheduler::run(boost::system::error_code&) ()
      #6  0x000055555566b00c in ?? ()
      #7  0x00007ffff6125d4f in execute_native_thread_routine () at
      /build/gcc/src/gcc/libstdc++-v3/src/c++11/thread.cc:80
      #8  0x00007ffff63fb075 in start_thread () from /usr/lib/libpthread.so.0
      #9  0x00007ffff57fa53f in clone () from /usr/lib/libc.so.6
      (gdb)
```

```
2018-07-26 05:05:17     @anonimal       Reverting to 110b2c0a, I can't repro with clang now.                                                       
2018-07-26 05:06:54     @anonimal       Literally makes no sense because there are no special Release flags aside from NDEBUG
```

Possible pessimizations. Yay clang (or CMake?) bug.

**Comment by anonimal** [comment]
Reproducible on masOS. We'll have to massage something out of 034e947da5b1aa62d6aff7e297599bd0d2a5321e before next Wednesday's release.
